[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10"
ethers-core = "2.0.14"
evm-rpc-canister-types = "1.0.0"
generic-array = "1.0.0"
getrandom = { version = "0.2", features = ["custom"] } 
hex = "0.4.3"
ic-cdk = "0.13"
ic-cdk-timers = "0.7"   # Feel free to remove this dependency if you don't need timers
k256 = "0.13.3"
serde = "1.0.197"
serde_bytes = "0.11.14"
serde_json = "1.0.116"
sha2 = "0.10.8"
alloy = { git = "https://github.com/ic-alloy/ic-alloy.git", tag = "v0.3.5-icp.1", default-features = false, features = [
  "icp",
  "sol-types",
  "json",
  "contract",
  "rlp", 
] }
alloy-primitives = "0.8.18"
tower = "0.5.1"
alloy-rpc-types-eth = "0.9.2"
alloy-rlp = "0.3.10"